In [2]:
import json
from sklearn.model_selection import train_test_split
import random

In [3]:
class Sentiment:
    NEGATIVE="NEGATIVE"
    NEUTRAL="NEUTRAL"
    POSITIVE="POSITIVE"

class Review:
    def __init__(self,text,score):
        self.text=text
        self.score=score
        self.sentiment= self.get_sentiment()
        
    def get_sentiment(self):
        if self.score<=2:
            return Sentiment.NEGATIVE
        elif self.score==3:
            return Sentiment.NEUTRAL
        else:
            return Sentiment.POSITIVE
        
class ReviewContainer:
    def __init__(self,reviews):
        self.reviews=reviews
            
    def get_text(self):
        return[x.text for x in self.reviews]
    def get_sentiment(self):
        return[x.sentiment for x in self.reviews]
            
    def evenly_distribute(self):
        negative=list(filter(lambda x:x.sentiment==Sentiment.NEGATIVE,self.reviews))
        possitive=list(filter(lambda x:x.sentiment==Sentiment.POSITIVE,self.reviews))
        shrunk_possitive=possitive[:len(negative)]
        self.reviews=negative+shrunk_possitive
        random.shuffle(self.reviews)
                        
    

In [4]:

files_name="E:/Books_small_10000.json"
reviews=[]
with open(files_name) as f:
    for line in f:
        review=json.loads(line)
        reviews.append(Review(review['reviewText'],review['overall']))
# reviews[100].sentiment

In [5]:
#x=[x.text for x in reviews]
#y=[x.sentiment for x in reviews]

In [6]:
training,test=train_test_split(reviews,test_size=0.33, random_state=42)
train_container=ReviewContainer(training)
test_container=ReviewContainer(test)

#len(count.reviews)

In [7]:
#x_train=[x.text for x in training]
#y_train=[x.sentiment for x in training]
#x_test=[x.text for x in test]
#y_test=[x.sentiment for x in test]

#another way bcz of proffe
train_container.evenly_distribute()
test_container.evenly_distribute()
x_train=train_container.get_text()
y_train=train_container.get_sentiment()
x_test=test_container.get_text()
y_test=test_container.get_sentiment()
y_train.count(Sentiment.POSITIVE)
#y_train.count(Sentiment.NEGATIVE)

436

In [8]:
y_test[2]

len(y_test)

416

In [9]:
#bag words algorithum "countvectorizer"

#fit and transform are different fun

#vectorizer.fit(train_x)
#train_x_vector=vectorizer.transform(train_x)

In [71]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
import numpy as np 
# x_train=np.array(train_x.reshape(-1,1))
vectorizer=TfidfVectorizer()
# vectorizer.fit(train_x)
vectorizer.fit(x_train)
train_x_vectors = vectorizer.transform(x_train).toarray()
# vectorizer.fit(test_x)
test_x_vectors = vectorizer.transform(x_test).toarray()
#train_x_vectors = vectorizer.transform(train_x)


In [58]:
train_x_vectors.shape,test_x_vectors.shape

((872, 8906), (416, 8906))

In [59]:
#del train_x_vectors,test_x_vectors

In [60]:
type(train_x_vectors)

numpy.ndarray

#classification

svm

In [61]:
from sklearn import svm
cls_svm=svm.SVC(C=16,kernel='linear',gamma='auto')
cls_svm.fit(train_x_vectors,y_train)
cls_svm.predict(np.array(test_x_vectors[0]).reshape(1,-1))

array(['NEGATIVE'], dtype='<U8')

In [79]:
print(test_x_vectors[0])


[0. 0. 0. ... 0. 0. 0.]


In [80]:
x_test[0]

'This book is outstanding. The format is user friendly and it covers the core with lots of examples. It is well worth the purchase.'

In [63]:
test_x_vectors.shape,train_x_vectors.shape

((416, 8906), (872, 8906))

decision tree

In [64]:
from sklearn.tree import DecisionTreeClassifier
cls_dec=DecisionTreeClassifier()
cls_dec.fit(train_x_vectors,y_train)
cls_dec.predict(np.array(test_x_vectors[0]).reshape(1,-1))

array(['NEGATIVE'], dtype='<U8')

naive base

In [65]:
from sklearn.naive_bayes import GaussianNB
cls_nav=GaussianNB()
cls_nav.fit(train_x_vectors,y_train)
cls_nav.predict(np.array(test_x_vectors[0]).reshape(1,-1))

array(['POSITIVE'], dtype='<U8')

logistic regression

In [66]:
from sklearn.linear_model import LogisticRegression

In [67]:
cls_log=LogisticRegression()
cls_log.fit(train_x_vectors,y_train)
cls_log.predict(np.array(test_x_vectors[0]).reshape(1,-1))

C:\Users\Bilal K P\New folder\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array(['POSITIVE'], dtype='<U8')

evaluation

mean accuracy

In [81]:
cls_svm.score(test_x_vectors,y_test)

0.8028846153846154

In [82]:
cls_dec.score(test_x_vectors,y_test)

0.6538461538461539

In [83]:
cls_log.score(test_x_vectors,y_test)

0.8028846153846154

In [84]:
from sklearn.metrics import f1_score

In [85]:
f1_score(y_test,cls_svm.predict(test_x_vectors),average=None,labels=[Sentiment.POSITIVE,Sentiment.NEGATIVE,Sentiment.NEUTRAL])

C:\Users\Bilal K P\New folder\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Bilal K P\New folder\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


array([0.80288462, 0.80288462, 0.        ])

In [86]:
f1_score(y_test,cls_nav.predict(test_x_vectors),average=None,labels=[Sentiment.POSITIVE,Sentiment.NEGATIVE,Sentiment.NEUTRAL])

C:\Users\Bilal K P\New folder\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Bilal K P\New folder\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


array([0.65693431, 0.66508314, 0.        ])

In [87]:
f1_score(y_test,cls_dec.predict(test_x_vectors),average=None,labels=[Sentiment.POSITIVE,Sentiment.NEGATIVE,Sentiment.NEUTRAL])

C:\Users\Bilal K P\New folder\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Bilal K P\New folder\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


array([0.64179104, 0.66511628, 0.        ])

In [88]:
f1_score(y_test,cls_log.predict(test_x_vectors),average=None,labels=[Sentiment.POSITIVE,Sentiment.NEGATIVE,Sentiment.NEUTRAL])

C:\Users\Bilal K P\New folder\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Bilal K P\New folder\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


array([0.80097087, 0.8047619 , 0.        ])

In [89]:
y_test.count(Sentiment.NEGATIVE)

208

In [90]:
test_set=['i thoroughly enjoy this','bad book','waste one','not bad']
new_set=vectorizer.transform(test_set)

In [91]:
print(np.array(new_set))

  (0, 7982)	0.8223446717804048
  (0, 7976)	0.18922659430868694
  (0, 2686)	0.5366027737542121
  (1, 991)	0.38084994261623106
  (1, 708)	0.9246368591015682
  (2, 8614)	0.8913026725152257
  (2, 5514)	0.45340880667143674
  (3, 5408)	0.45992442160984076
  (3, 708)	0.8879580656803865


In [92]:
from scipy.sparse import csr_matrix
temp = csr_matrix(new_set)

In [93]:
new_set = temp.todense()#new_set is very small so to much zeros are coming.error called sparse matrics.so python was compressed in sparse object

In [94]:
cls_log.predict(new_set)

array(['POSITIVE', 'NEGATIVE', 'NEGATIVE', 'NEGATIVE'], dtype='<U8')

In [95]:
cls_svm.predict(new_set)

array(['POSITIVE', 'NEGATIVE', 'NEGATIVE', 'NEGATIVE'], dtype='<U8')

In [100]:
from sklearn.model_selection import GridSearchCV

parameters = {'kernel':('linear', 'rbf'), 'C':[0.1,1,8,16,32]}
svc = svm.SVC()
clf = GridSearchCV(svc, parameters, cv=5)
clf.fit(train_x_vectors,y_train)

C:\Users\Bilal K P\New folder\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Bilal K P\New folder\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Bilal K P\New folder\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Bilal K P\New folder\lib\site-packages\sklearn\svm\base

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'kernel': ('linear', 'rbf'), 'C': [0.1, 1, 8, 16, 32]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [ ]:
x_train.shape

In [ ]:
print(test_x_vectors[0].text)

In [101]:
import pickle
with open('category classification.pkl','wb') as f:
    pickle.dump(clf,f)